    const councils = [

{
  number: 1,
  name: "Andhra Pradesh State Organic Products Certification Authority (APSOPCA)",
  head: "Dr A Trivikrama Reddy",
  responsible: "Dr G Yugandhar",
  phone1: "8074707792",
  phone2: "9739316931",
  email1: "atr2050@gmail.com",
  email2: "gokidiy@gmail.com",
  address: "ANGRAU, Lam Farm, Guntur, Andhra Pradesh - 522034",
  category: "AP Regional Council",

},

{
  number: 2,
  name: "Timbaktu Collective",
  head: "Gondi Mahesh",
  responsible: "M Ramesh Kumar",
  phone1: "08559240149",
  phone2: "8309499800",
  email1: "info@timbaktu.org",
  email2: "info@timabktu.org",
  address: "Chennekothapalli, Sri Sathya Sai District, AP",
    category: "AP Regional Council",

},

{
  number: 3,
  name: "Centre for Sustainable Agriculture (CSA)",
  head: "Dr G V Ramanjaneyulu",
  responsible: "Chandrakala P",
  phone1: "9000005840",
  phone2: "9000699702",
  email1: "ramoo@csa-india.org",
  email2: "chandrakala@csa-india.org",
  address: "Tarnaka, Hyderabad",
  category: "telangana Regional Council",
},

{
  number: 4,
  name: "Ekalavya Foundation",
  head: "P. Venguopal Reddy",
  responsible: "Kubide Madhukar",
  phone1: "04027674649",
  phone2: "9701814310",
  email1: "pvg@ekalavya.net",
  email2: "madhukubide@gmail.com",
  address: "Hyderabad",
    category: "telangana Regional Council",

},
{
  number: 5,
  name: "Karnataka State Seed and Organic Certification Agency",
  head: "Mr Karunakara J",
  responsible: "Mr H Ravindranath",
  phone1: "08023419418",
  phone2: "9448990379",
  email1: "dscbng@gmail.com",
  email2: "ksocabng@gmail.com",
  address: "Hebbal, Bengaluru",
  category: "karnataka Regional Council",
},

{
  number: 6,
  name: "Phaladaayi Foundation",
  head: "Umesh Adiga",
  responsible: "Govind Kumar",
  phone1: "9900039423",
  phone2: "9900039406",
  email1: "pgs@phaladaagro.com",
  email2: "pgs@phaladaagro.com",
  address: "Rajarajeshwari Nagar, Bengaluru",
  category: "karnataka Regional Council",

},

{
  number: 7,
  name: "Aditi Organic Certifications Pvt Ltd",
  head: "Kavya HP",
  responsible: "Abhishek Mishra",
  phone1: "9481037555",
  phone2: "7619102658",
  email1: "kavya@aditicert.net",
  email2: "abhishek@aditicert.net",
  address: "Rajajinagar, Bengaluru",
  category: "karnataka Regional Council",
},

{
  number: 8,
  name: "Reliable Organic Certification Organization",
  head: "Nagaraja L B",
  responsible: "Girish N M",
  phone1: "07026243618",
  phone2: "7026243618",
  email1: "reliableoco@gmail.com",
  email2: "reliableoco@gmail.com",
  address: "Yelahanka, Bengaluru",
  category: "karnataka Regional Council",
},

{
  number: 9,
  name: "Thanal",
  head: "Jayakumar C",
  responsible: "Manju M Nair",
  phone1: "04712727150",
  phone2: "9400411291",
  email1: "jayakumar.c@gmail.com",
  email2: "hr@thanal.co.in",
  address: "Trivandrum, Kerala",
  category: "kerala Regional Council",  
},{
  number: 10,
  name: "Qmark International Certifications Pvt Ltd",
  head: "Ranjan Baruah",
  responsible: "Ratnesh Singh",
  phone1: "8822249901",
  phone2: "9826086446",
  email1: "ranjanbaruah38@gmail.com",
  email2: "wcdcsidhi@gmail.com",
  address: "Guwahati, Assam",
  category: "assam Regional Council",
},

{
  number: 11,
  name: "APOF Organic Certification Agency",
  head: "Mr Nirmal D",
  responsible: "Mr Nirmal D",
  phone1: "8806230301",
  phone2: "8806230301",
  email1: "info@aoca.in",
  email2: "info@aoca.in",
  address: "Pune, Maharashtra",
  category: "maharashtra Regional Council",
},

{
  number: 12,
  name: "Faircert Certification Services Pvt Ltd",
  head: "Dr Pushkar Kulshrest",
  responsible: "Dr Pushkar Kulshrest",
  phone1: "9589309876",
  phone2: "9589309876",
  email1: "pushkar97@gmail.com",
  email2: "INFO@FAIRCERT.COM",
  address: "Ahmedabad, Gujarat",
  category: "gujarat Regional Council",
},

{
  number: 13,
  name: "Natural Organic Certification Association",
  head: "Sanjay Deshmukh",
  responsible: "Jayprakash Sakle",
  phone1: "912025237677",
  phone2: "9511858669",
  email1: "nocaindia@gmail.com",
  email2: "jaysakle@yahoo.com",
  address: "Pune, Maharashtra",
  category: "maharashtra Regional Council",
},

{
  number: 14,
  name: "Global Certification Society",
  head: "B C Awasthi",
  responsible: "Vikas Kumar",
  phone1: "01894234230",
  phone2: "9413919330",
  email1: "chairman@glocert.org",
  email2: "ceo@glocert.org",
  address: "Kangra, Himachal Pradesh",
  category: "himachal Pradesh Regional Council",
},

{
  number: 15,
  name: "Trace Assure Global",
  head: "Yogesh Kumar",
  responsible: "Yogesh Kumar",
  phone1: "09410080404",
  phone2: "9410090404",
  email1: "traceassure@gmail.com",
  email2: "traceassure@gmail.com",
  address: "New Delhi",
  category: "delhi Regional Council",
},
];

export default councils;